# Generated by Django 4.2.1 on 2023-05-29 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0002_admins_users_admin_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='account_status',
            field=models.CharField(choices=[('pending', 'pending'), ('running', 'running'), ('broken', 'broken')], default='pending', max_length=100),
        ),
        migrations.AddField(
            model_name='users',
            name='total_contact',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='users',
            name='total_customers',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='users',
            name='total_mail_id',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='users',
            name='email',
            field=models.CharField(default='', max_length=100),
        ),
    ]
