# Generated by Django 4.2.1 on 2023-05-29 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0003_users_account_status_users_total_contact_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='account_status',
        ),
        migrations.RemoveField(
            model_name='users',
            name='total_contact',
        ),
        migrations.RemoveField(
            model_name='users',
            name='total_customers',
        ),
        migrations.RemoveField(
            model_name='users',
            name='total_mail_id',
        ),
        migrations.AddField(
            model_name='admins',
            name='account_status',
            field=models.CharField(choices=[('pending', 'pending'), ('running', 'running'), ('broken', 'broken')], default='pending', max_length=100),
        ),
        migrations.AddField(
            model_name='admins',
            name='total_contact',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='admins',
            name='total_customers',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='admins',
            name='total_mail_id',
            field=models.CharField(default='', max_length=100),
        ),
    ]
