# Generated by Django 4.2.1 on 2023-05-30 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0004_remove_users_account_status_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='admins',
            old_name='username',
            new_name='first_name',
        ),
        migrations.AddField(
            model_name='admins',
            name='last_name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
