# Generated by Django 4.2.1 on 2023-05-30 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0005_rename_username_admins_first_name_admins_last_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='BotCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin_email', models.CharField(max_length=100)),
                ('Bot_contact', models.CharField(max_length=100)),
            ],
        ),
    ]
