# Generated by Django 4.2.1 on 2023-05-30 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0006_botcollection'),
    ]

    operations = [
        migrations.RenameField(
            model_name='admins',
            old_name='first_name',
            new_name='username',
        ),
        migrations.RemoveField(
            model_name='admins',
            name='last_name',
        ),
        migrations.AddField(
            model_name='users',
            name='first_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='users',
            name='last_name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
