# Generated by Django 4.2.1 on 2023-05-30 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0007_rename_first_name_admins_username_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admins',
            name='contact',
            field=models.IntegerField(max_length=20),
        ),
        migrations.AlterField(
            model_name='botcollection',
            name='Bot_contact',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='users',
            name='contact',
            field=models.IntegerField(max_length=20),
        ),
    ]
