# Generated by Django 4.2.1 on 2023-05-30 04:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0009_alter_admins_contact_alter_users_contact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='name',
        ),
    ]
