# Generated by Django 4.2.1 on 2023-05-30 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0011_alter_users_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='botcollection',
            name='Bot_Task',
            field=models.CharField(choices=[('intelligent_bot', 'intelligent_bot'), ('collect_data', 'collect_data')], default='collect_data', max_length=20),
        ),
        migrations.AddField(
            model_name='botcollection',
            name='Bot_name',
            field=models.CharField(default='', max_length=20),
        ),
    ]
