# Generated by Django 4.2.1 on 2023-05-31 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0013_alter_admins_account_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='botcollection',
            name='Bot_Status',
            field=models.CharField(choices=[('running', 'running'), ('not_running', 'not_running')], default='running', max_length=20),
        ),
    ]
