# Generated by Django 4.2.1 on 2023-05-31 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0014_botcollection_bot_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='waiting_for',
            field=models.CharField(default='', max_length=100),
        ),
    ]
