# Generated by Django 4.2.1 on 2023-06-01 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0015_users_waiting_for'),
    ]

    operations = [
        migrations.CreateModel(
            name='Templates_v1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bot_number', models.CharField(max_length=100)),
                ('first_name', models.CharField(choices=[('enable', 'enable'), ('disable', 'disable')], max_length=50)),
                ('last_name', models.CharField(choices=[('enable', 'enable'), ('disable', 'disable')], max_length=50)),
                ('contact', models.CharField(choices=[('enable', 'enable'), ('disable', 'disable')], max_length=50)),
                ('email', models.CharField(choices=[('enable', 'enable'), ('disable', 'disable')], max_length=50)),
                ('quetion_1', models.CharField(choices=[('enable', 'enable'), ('disable', 'disable')], max_length=50)),
                ('quetion_2', models.CharField(choices=[('enable', 'enable'), ('disable', 'disable')], max_length=50)),
                ('quetion_3', models.CharField(choices=[('enable', 'enable'), ('disable', 'disable')], max_length=50)),
                ('quetion_4', models.CharField(choices=[('enable', 'enable'), ('disable', 'disable')], max_length=50)),
                ('quetion_5', models.CharField(choices=[('enable', 'enable'), ('disable', 'disable')], max_length=50)),
            ],
        ),
    ]
