# Generated by Django 4.2.1 on 2023-06-01 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0016_templates_v1'),
    ]

    operations = [
        migrations.AddField(
            model_name='templates_v1',
            name='template_name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
