# Generated by Django 4.2.1 on 2023-06-01 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0017_templates_v1_template_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='templates_v1',
            name='admin_email',
            field=models.CharField(default='', max_length=100),
        ),
    ]
