# Generated by Django 4.2.1 on 2023-06-01 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0019_remove_templates_v1_admin_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='templates_v1',
            name='template_status',
            field=models.CharField(default='', max_length=100),
        ),
    ]
