# Generated by Django 4.2.1 on 2023-06-02 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0024_alter_templates_v1_contact_alter_templates_v1_email_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='botcollection',
            old_name='Bot_Task',
            new_name='Bot_Template',
        ),
        migrations.AlterField(
            model_name='templates_v1',
            name='quetion_1',
            field=models.CharField(default='disable', max_length=50),
        ),
        migrations.AlterField(
            model_name='templates_v1',
            name='quetion_2',
            field=models.CharField(default='disable', max_length=50),
        ),
        migrations.AlterField(
            model_name='templates_v1',
            name='quetion_3',
            field=models.CharField(default='disable', max_length=50),
        ),
        migrations.AlterField(
            model_name='templates_v1',
            name='quetion_4',
            field=models.CharField(default='disable', max_length=50),
        ),
        migrations.AlterField(
            model_name='templates_v1',
            name='quetion_5',
            field=models.CharField(default='disable', max_length=50),
        ),
    ]
