# Generated by Django 4.2.1 on 2023-06-02 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0026_alter_templates_v1_first_name_q'),
    ]

    operations = [
        migrations.AddField(
            model_name='templates_v1',
            name='welcome_message',
            field=models.CharField(default='', max_length=100),
        ),
    ]
