# Generated by Django 4.2.1 on 2023-06-02 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0028_alter_templates_v1_welcome_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='templates_v1',
            name='end_message',
            field=models.CharField(default='thank you', max_length=100),
        ),
    ]
