# Generated by Django 4.2.1 on 2023-06-02 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0031_users_contact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='count',
        ),
        migrations.AlterField(
            model_name='users',
            name='bot_contact',
            field=models.CharField(default='', max_length=20),
        ),
    ]
