# Generated by Django 4.2.1 on 2023-06-03 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0033_alter_templates_v1_end_message_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin_email', models.CharField(max_length=100)),
                ('media', models.CharField(max_length=100)),
                ('media_type', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='templates_v1',
            name='confirmation_message',
            field=models.CharField(default='confirm your details', max_length=500),
        ),
    ]
