# Generated by Django 4.2.1 on 2023-06-03 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0034_media_templates_v1_confirmation_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='question_1',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='users',
            name='question_2',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='users',
            name='question_3',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='users',
            name='question_4',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='users',
            name='question_5',
            field=models.CharField(default='', max_length=100),
        ),
    ]
