# Generated by Django 4.2.1 on 2023-06-03 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0035_users_question_1_users_question_2_users_question_3_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='templates_v1',
            name='brain_model',
            field=models.CharField(default='fully-intelligent', max_length=500),
        ),
    ]
