# Generated by Django 4.2.1 on 2023-06-03 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0036_templates_v1_brain_model'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Media',
        ),
        migrations.AddField(
            model_name='templates_v1',
            name='media',
            field=models.FileField(default='', upload_to='whatsup/'),
        ),
        migrations.AddField(
            model_name='templates_v1',
            name='media_type',
            field=models.CharField(default='', max_length=100),
        ),
    ]
