# Generated by Django 4.2.1 on 2023-06-03 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0037_delete_media_templates_v1_media_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='templates_v1',
            old_name='media',
            new_name='confirmation_message_media',
        ),
        migrations.RenameField(
            model_name='templates_v1',
            old_name='media_type',
            new_name='confirmation_message_media_type',
        ),
        migrations.AddField(
            model_name='templates_v1',
            name='end_message_media',
            field=models.FileField(default='', upload_to='whatsup/'),
        ),
        migrations.AddField(
            model_name='templates_v1',
            name='end_message_media_type',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='templates_v1',
            name='welcome_message_media',
            field=models.FileField(default='', upload_to='whatsup/'),
        ),
        migrations.AddField(
            model_name='templates_v1',
            name='welcome_message_media_type',
            field=models.CharField(default='', max_length=100),
        ),
    ]
